<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="de_DE" sourcelanguage="en">
<context>
    <name>AppInfo</name>
    <message>
        <location filename="store.py" line="386"/>
        <source>Version</source>
        <translation>Version</translation>
    </message>
    <message>
        <location filename="store.py" line="387"/>
        <source>Description</source>
        <translation>Beschreibung</translation>
    </message>
    <message>
        <location filename="store.py" line="388"/>
        <source>Author</source>
        <translation>Autor</translation>
    </message>
    <message>
        <location filename="store.py" line="389"/>
        <source>Firmware</source>
        <translation>Firmware</translation>
    </message>
    <message>
        <location filename="store.py" line="390"/>
        <source>Set</source>
        <translation>Baukasten</translation>
    </message>
    <message>
        <location filename="store.py" line="391"/>
        <source>Model</source>
        <translation>Modell</translation>
    </message>
    <message>
        <location filename="store.py" line="392"/>
        <source>Category</source>
        <translation>Kategorie</translation>
    </message>
    <message>
        <location filename="store.py" line="445"/>
        <source>Inst.</source>
        <translation>Inst.</translation>
    </message>
</context>
<context>
    <name>Category</name>
    <message>
        <location filename="store.py" line="36"/>
        <source>System</source>
        <translation>System</translation>
    </message>
    <message>
        <location filename="store.py" line="38"/>
        <source>Models</source>
        <translation>Modelle</translation>
    </message>
    <message>
        <location filename="store.py" line="40"/>
        <source>Tools</source>
        <translation>Werkzeuge</translation>
    </message>
    <message>
        <location filename="store.py" line="44"/>
        <source>Demos</source>
        <translation>Demos</translation>
    </message>
    <message>
        <location filename="store.py" line="50"/>
        <source>&lt;unknown&gt;</source>
        <translation>&lt;unbekannt&gt;</translation>
    </message>
</context>
<context>
    <name>Error</name>
    <message>
        <location filename="store.py" line="272"/>
        <source>Not a valid zip file</source>
        <translation>Keine gültige ZIP-Datei</translation>
    </message>
    <message>
        <location filename="store.py" line="291"/>
        <source>Manifest does not contain a UUID!</source>
        <translation>Manifest enthält keine UUID!</translation>
    </message>
    <message>
        <location filename="store.py" line="304"/>
        <source>Unable to create target dir!</source>
        <translation>Kann Zielverzeichnis nicht erstellen!</translation>
    </message>
    <message>
        <location filename="store.py" line="703"/>
        <source>Error</source>
        <translation>Fehler</translation>
    </message>
    <message>
        <location filename="store.py" line="459"/>
        <source>Update app path mismatch.</source>
        <translation>Aktualisierungspfad stimmt nicht überein.</translation>
    </message>
    <message>
        <location filename="store.py" line="480"/>
        <source>Delete app path not found!</source>
        <translation>Zu löschender Pfad nicht gefunden!</translation>
    </message>
    <message>
        <location filename="store.py" line="486"/>
        <source>Unable to remove app</source>
        <translation>Kann Applikation nicht löschen</translation>
    </message>
    <message>
        <location filename="store.py" line="737"/>
        <source>no version info</source>
        <translation>Keine Versionsinformation</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="store.py" line="805"/>
        <source>Store</source>
        <translation>Store</translation>
    </message>
</context>
<context>
    <name>Menu</name>
    <message>
        <location filename="store.py" line="420"/>
        <source>Install</source>
        <translation>Installieren</translation>
    </message>
    <message>
        <location filename="store.py" line="426"/>
        <source>Uninstall</source>
        <translation>Deinstall.</translation>
    </message>
    <message>
        <location filename="store.py" line="432"/>
        <source>Update</source>
        <translation>Aktualisieren</translation>
    </message>
</context>
<context>
    <name>NetError</name>
    <message>
        <location filename="store.py" line="187"/>
        <source>No error</source>
        <translation>Kein Fehler</translation>
    </message>
    <message>
        <location filename="store.py" line="188"/>
        <source>Connection Refused</source>
        <translation>Verbindung verweigert</translation>
    </message>
    <message>
        <location filename="store.py" line="189"/>
        <source>Server closed connection</source>
        <translation>Server hat Verbindung geschlossen</translation>
    </message>
    <message>
        <location filename="store.py" line="190"/>
        <source>Host not found</source>
        <translation>Server nicht gefunden</translation>
    </message>
    <message>
        <location filename="store.py" line="191"/>
        <source>Connection timed out</source>
        <translation>Zeitüberschreitung in Verbindung</translation>
    </message>
    <message>
        <location filename="store.py" line="192"/>
        <source>Connection cancelled</source>
        <translation>Verbindung abgebrochen</translation>
    </message>
    <message>
        <location filename="store.py" line="193"/>
        <source>SSL handshake failed</source>
        <translation>SSL-Aushandlung fehlgeschlagen</translation>
    </message>
    <message>
        <location filename="store.py" line="194"/>
        <source>Network Failure</source>
        <translation>Netzwerkfehler</translation>
    </message>
    <message>
        <location filename="store.py" line="214"/>
        <source>Network error:</source>
        <translation>Netzwerkfehler:</translation>
    </message>
    <message>
        <location filename="store.py" line="128"/>
        <source>Unknown network error</source>
        <translation type="obsolete">Unbekannter Netzwerkfehler</translation>
    </message>
</context>
<context>
    <name>NewRepo</name>
    <message>
        <location filename="store.py" line="347"/>
        <source>New</source>
        <translation>Neu</translation>
    </message>
    <message>
        <location filename="store.py" line="358"/>
        <source>Name:</source>
        <translation>Name:</translation>
    </message>
    <message>
        <location filename="store.py" line="367"/>
        <source>User:</source>
        <translation>Nutzer:</translation>
    </message>
    <message>
        <location filename="store.py" line="370"/>
        <source>Repository:</source>
        <translation>Repository:</translation>
    </message>
    <message>
        <location filename="store.py" line="363"/>
        <source>Github:</source>
        <translation>Github:</translation>
    </message>
</context>
<context>
    <name>menu</name>
    <message>
        <location filename="store.py" line="809"/>
        <source>New</source>
        <translation>Neu</translation>
    </message>
    <message>
        <location filename="store.py" line="811"/>
        <source>Remove</source>
        <translation>Entfernen</translation>
    </message>
    <message>
        <location filename="store.py" line="817"/>
        <source>ftc</source>
        <translation>ftc</translation>
    </message>
</context>
</TS>
