<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="de_DE" sourcelanguage="en">
<context>
    <name>AppInfo</name>
    <message>
        <location filename="store.py" line="290"/>
        <source>Version</source>
        <translation>Version</translation>
    </message>
    <message>
        <location filename="store.py" line="291"/>
        <source>Description</source>
        <translation>Beschreibung</translation>
    </message>
    <message>
        <location filename="store.py" line="292"/>
        <source>Author</source>
        <translation>Autor</translation>
    </message>
    <message>
        <location filename="store.py" line="293"/>
        <source>Firmware</source>
        <translation>Firmware</translation>
    </message>
    <message>
        <location filename="store.py" line="294"/>
        <source>Set</source>
        <translation>Baukasten</translation>
    </message>
    <message>
        <location filename="store.py" line="295"/>
        <source>Model</source>
        <translation>Modell</translation>
    </message>
    <message>
        <location filename="store.py" line="296"/>
        <source>Category</source>
        <translation>Kategorie</translation>
    </message>
    <message>
        <location filename="store.py" line="343"/>
        <source>Inst.</source>
        <translation>Inst.</translation>
    </message>
</context>
<context>
    <name>Category</name>
    <message>
        <location filename="store.py" line="23"/>
        <source>System</source>
        <translation>System</translation>
    </message>
    <message>
        <location filename="store.py" line="25"/>
        <source>Models</source>
        <translation>Modelle</translation>
    </message>
    <message>
        <location filename="store.py" line="27"/>
        <source>Tools</source>
        <translation>Werkzeuge</translation>
    </message>
    <message>
        <location filename="store.py" line="31"/>
        <source>Demos</source>
        <translation>Demos</translation>
    </message>
    <message>
        <location filename="store.py" line="37"/>
        <source>&lt;unknown&gt;</source>
        <translation>&lt;unbekannt&gt;</translation>
    </message>
</context>
<context>
    <name>Error</name>
    <message>
        <location filename="store.py" line="235"/>
        <source>Not a valid zip file</source>
        <translation>Keine gültige ZIP-Datei</translation>
    </message>
    <message>
        <location filename="store.py" line="254"/>
        <source>Manifest does not contain a UUID!</source>
        <translation>Manifest enthält keine UUID!</translation>
    </message>
    <message>
        <location filename="store.py" line="267"/>
        <source>Unable to create target dir!</source>
        <translation>Kann Zielverzeichnis nicht erstellen!</translation>
    </message>
    <message>
        <location filename="store.py" line="556"/>
        <source>Error</source>
        <translation>Fehler</translation>
    </message>
    <message>
        <location filename="store.py" line="357"/>
        <source>Update app path mismatch.</source>
        <translation>Aktualisierungspfad stimmt nicht überein.</translation>
    </message>
    <message>
        <location filename="store.py" line="378"/>
        <source>Delete app path not found!</source>
        <translation>Zu löschender Pfad nicht gefunden!</translation>
    </message>
    <message>
        <location filename="store.py" line="384"/>
        <source>Unable to remove app</source>
        <translation>Kann Applikation nicht löschen</translation>
    </message>
    <message>
        <location filename="store.py" line="595"/>
        <source>no version info</source>
        <translation>Keine Versionsinformation</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="store.py" line="638"/>
        <source>Store</source>
        <translation>Laden</translation>
    </message>
</context>
<context>
    <name>Menu</name>
    <message>
        <location filename="store.py" line="318"/>
        <source>Install</source>
        <translation>Installieren</translation>
    </message>
    <message>
        <location filename="store.py" line="324"/>
        <source>Uninstall</source>
        <translation>Deinstall.</translation>
    </message>
    <message>
        <location filename="store.py" line="330"/>
        <source>Update</source>
        <translation>Aktualisieren</translation>
    </message>
</context>
<context>
    <name>NetError</name>
    <message>
        <location filename="store.py" line="153"/>
        <source>No error</source>
        <translation>Kein Fehler</translation>
    </message>
    <message>
        <location filename="store.py" line="154"/>
        <source>Connection Refused</source>
        <translation>Verbindung verweigert</translation>
    </message>
    <message>
        <location filename="store.py" line="155"/>
        <source>Server closed connection</source>
        <translation>Server hat Verbindung geschlossen</translation>
    </message>
    <message>
        <location filename="store.py" line="156"/>
        <source>Host not found</source>
        <translation>Server nicht gefunden</translation>
    </message>
    <message>
        <location filename="store.py" line="157"/>
        <source>Connection timed out</source>
        <translation>Zeitüberschreitung in Verbindung</translation>
    </message>
    <message>
        <location filename="store.py" line="158"/>
        <source>Connection cancelled</source>
        <translation>Verbindung abgebrochen</translation>
    </message>
    <message>
        <location filename="store.py" line="159"/>
        <source>SSL handshake failed</source>
        <translation>SSL-Aushandlung fehlgeschlagen</translation>
    </message>
    <message>
        <location filename="store.py" line="160"/>
        <source>Network Failure</source>
        <translation>Netzwerkfehler</translation>
    </message>
    <message>
        <location filename="store.py" line="177"/>
        <source>Network error:</source>
        <translation>Netzwerkfehler:</translation>
    </message>
    <message>
        <location filename="store.py" line="128"/>
        <source>Unknown network error</source>
        <translation type="obsolete">Unbekannter Netzwerkfehler</translation>
    </message>
</context>
</TS>
